# Generated by Django 5.1.7 on 2025-03-13 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoaderManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loader_name', models.CharField(max_length=30)),
                ('loader_type', models.CharField(max_length=20)),
                ('loader_details', models.CharField(max_length=200)),
                ('creation_date', models.DateField()),
                ('connection', models.CharField(max_length=30)),
            ],
        ),
    ]
