# Generated by Django 5.1.7 on 2025-03-13 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loaders_manager', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LoaderManager',
            new_name='Loader',
        ),
    ]
